"""
Fully Autonomous Auto-Fixer
Automatically fixes vulnerabilities without user prompts
"""

import os
import re
from typing import Dict, List, Tuple, Optional
from pathlib import Path


class AutoFixer:
    """Automatically fix security vulnerabilities"""
    
    def __init__(self, repo_path: str):
        self.repo_path = Path(repo_path)
        self.env_file = self.repo_path / ".env"
        self.gitignore = self.repo_path / ".gitignore"
        self.fixes_applied: List[Dict] = []
    
    def fix_all(self, findings: List[Dict]) -> Dict:
        """
        Automatically fix all fixable vulnerabilities
        
        Returns summary of fixes applied
        """
        results = {
            "secrets_extracted": 0,
            "files_modified": [],
            "env_created": False,
            "gitignore_updated": False,
        }
        
        # Group findings by type
        secrets = [f for f in findings if f.get("type") in ["Generic API Key", "GitHub Token", "AWS Key", "Database Password"]]
        
        # Fix secrets
        if secrets:
            secret_results = self._extract_secrets_to_env(secrets)
            results.update(secret_results)
        
        return results
    
    def _extract_secrets_to_env(self, secrets: List[Dict]) -> Dict:
        """Extract hardcoded secrets to .env file"""
        results = {
            "secrets_extracted": 0,
            "files_modified": set(),
            "env_created": False,
            "gitignore_updated": False,
        }
        
        env_vars = {}
        file_changes = {}
        
        for secret in secrets:
            file_path = secret.get("file", "")
            line_num = secret.get("line_number", 0)
            value = secret.get("value", "")
            secret_type = secret.get("type", "")
            
            if not file_path or not value:
                continue
            
            # Generate env var name
            var_name = self._generate_env_var_name(secret_type, file_path)
            env_vars[var_name] = value
            
            # Track file changes
            if file_path not in file_changes:
                file_changes[file_path] = []
            file_changes[file_path].append({
                "line": line_num,
                "old_value": value,
                "var_name": var_name,
            })
        
        # Write .env file
        if env_vars:
            self._write_env_file(env_vars)
            results["env_created"] = True
            results["secrets_extracted"] = len(env_vars)
        
        # Update source files
        for file_path, changes in file_changes.items():
            if self._update_source_file(file_path, changes):
                results["files_modified"].add(file_path)
        
        # Update .gitignore
        if self._update_gitignore():
            results["gitignore_updated"] = True
        
        results["files_modified"] = list(results["files_modified"])
        return results
    
    def _generate_env_var_name(self, secret_type: str, file_path: str) -> str:
        """Generate appropriate env var name"""
        type_map = {
            "Generic API Key": "API_KEY",
            "GitHub Token": "GITHUB_TOKEN",
            "AWS Key": "AWS_ACCESS_KEY",
            "Database Password": "DB_PASSWORD",
        }
        
        base_name = type_map.get(secret_type, "SECRET")
        
        # Add file context if multiple secrets
        file_name = Path(file_path).stem.upper()
        return f"{file_name}_{base_name}"
    
    def _write_env_file(self, env_vars: Dict[str, str]):
        """Write environment variables to .env file"""
        lines = []
        
        if self.env_file.exists():
            # Append to existing
            lines = self.env_file.read_text().splitlines()
            lines.append("")
            lines.append("# Auto-extracted secrets by SentinelCI")
        else:
            lines.append("# Environment Variables")
            lines.append("# Auto-generated by SentinelCI")
            lines.append("")
        
        for var_name, value in env_vars.items():
            # Mask the value in .env for security
            lines.append(f"{var_name}={value}")
        
        self.env_file.write_text("\n".join(lines))
    
    def _update_source_file(self, file_path: str, changes: List[Dict]) -> bool:
        """Replace hardcoded secrets with env var references"""
        full_path = self.repo_path / file_path
        
        if not full_path.exists():
            return False
        
        try:
            content = full_path.read_text()
            lines = content.splitlines()
            
            # Sort changes by line number (reverse to maintain line numbers)
            changes.sort(key=lambda x: x["line"], reverse=True)
            
            for change in changes:
                line_idx = change["line"] - 1
                if 0 <= line_idx < len(lines):
                    old_line = lines[line_idx]
                    old_value = change["old_value"]
                    var_name = change["var_name"]
                    
                    # Replace the secret value with env var reference
                    # Detect language and use appropriate syntax
                    if file_path.endswith(".py"):
                        new_value = f'os.getenv("{var_name}")'
                        # Add import if not present
                        if "import os" not in content:
                            lines.insert(0, "import os")
                    elif file_path.endswith((".js", ".ts")):
                        new_value = f'process.env.{var_name}'
                    elif file_path.endswith(".yml") or file_path.endswith(".yaml"):
                        new_value = f"${{{var_name}}}"
                    else:
                        new_value = f"${var_name}"
                    
                    # Replace in line
                    new_line = old_line.replace(f'"{old_value}"', new_value)
                    new_line = new_line.replace(f"'{old_value}'", new_value)
                    lines[line_idx] = new_line
            
            # Write back
            full_path.write_text("\n".join(lines))
            return True
            
        except Exception:
            return False
    
    def _update_gitignore(self) -> bool:
        """Add .env to .gitignore if not present"""
        try:
            if self.gitignore.exists():
                content = self.gitignore.read_text()
                if ".env" in content:
                    return False  # Already there
                
                lines = content.splitlines()
            else:
                lines = []
            
            lines.append("")
            lines.append("# Environment variables (added by SentinelCI)")
            lines.append(".env")
            lines.append(".env.local")
            lines.append(".env.*.local")
            
            self.gitignore.write_text("\n".join(lines))
            return True
            
        except Exception:
            return False


def auto_fix_repository(repo_path: str, findings: List[Dict]) -> Dict:
    """
    Automatically fix all vulnerabilities in a repository
    
    Args:
        repo_path: Path to repository
        findings: List of security findings
    
    Returns:
        Summary of fixes applied
    """
    fixer = AutoFixer(repo_path)
    return fixer.fix_all(findings)
